services:
  api:
    build:
      target: base
    ports:
      - 9001:80
    volumes:
      - ./api:/app
  db:
    build:
      context: ./database
    container_name: markethunt-db-${APP_ENV?}