services:
  api:
    build:
      context: ./api
    container_name: markethunt-api-${APP_ENV?}
    restart: on-failure
  frontend:
    build:
      context: ./frontend
    container_name: markethunt-frontend-${APP_ENV?}
    restart: on-failure