name: Deploy to Prod

on:
  push:
    branches: master

env:
  API_ENV: .env
  WEB_CONFIG: config.php

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Context
      run: |
        pwd
        whoami
        date

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare Docker .env
      run: |
        mv .env.release .env
        echo "APP_ENV=prod" >> .env

    - name: Prepare API .env
      working-directory: api/config
      run: |
        rm $API_ENV
        echo "DB_DSN=\"${{ secrets.DB_DSN }}\"" >> $API_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $API_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $API_ENV
        echo "API_HOSTNAME=api.markethunt.win" >> $API_ENV
        echo "MARKETHUNT_APP_HOSTNAME=markethunt.win" >> $API_ENV
        echo "USE_REDIS=true" >> $API_ENV
        echo "REDIS_HOST=redis" >> $API_ENV
        echo "REDIS_PORT=6379" >> $API_ENV
        echo "REDIS_PREFIX=" >> $API_ENV

    - name: Prepare Frontend config.php
      working-directory: frontend/config
      run: |
        rm $WEB_CONFIG
        echo "<?php" >> $WEB_CONFIG
        echo "\$DB_USER = '${{ secrets.DB_USER }}';" >> $WEB_CONFIG
        echo "\$DB_PASSWORD = '${{ secrets.DB_PASSWORD }}';" >> $WEB_CONFIG
        echo "\$DB_HOST = '${{ secrets.DB_HOST }}';" >> $WEB_CONFIG
        echo "\$DB_DATABASE = 'markethunt';" >> $WEB_CONFIG

    - name: Build js
      working-directory: frontend/www-src
      run: |
        npm install
        npm run build-prod

    - name: Install SSH SSH key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.SSHKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy files to Prod
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        # exclusions must use full paths
        source: "./*,!.git*,!frontend/www-src"
        target: ${{ secrets.PROD_PATH }}
        rm: true

    - name: Build Containers
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} <<'ENDSSH'
        cd ${{ secrets.PROD_PATH }}
        docker compose up --build -d
        ENDSSH
